In [29]:

n = int(input("enter num to make list"))
list = []

def Calc(n):

 for i in range (1,n):
  if( i%3 == 0 ):
    list.append("Fizz")
  elif( i%5 == 0):
    list.append("buzz")
  else:
    list.append(str(i))
 

Calc(n)
print(list)

['1', '2', 'Fizz', '4', 'buzz', 'Fizz', '7', '8', 'Fizz', 'buzz', '11', 'Fizz', '13', '14']

Pandas Foundation

In [96]:
import pandas as pd

df = pd.DataFrame({
    'Name' : ['Ahmad','Hammi','Aybee','Jelani'],
    'City' : ['Kasur','Lahore','Lahore','Gujranwala'],
    'Age': [23,23,22,23.5],
    'GPA': [3.4 ,3.7 ,3.8,3.0]
})
print(df)

     Name        City   Age  GPA
0   Ahmad       Kasur  23.0  3.4
1   Hammi      Lahore  23.0  3.7
2   Aybee      Lahore  22.0  3.8
3  Jelani  Gujranwala  23.5  3.0

In [100]:
df = pd.read_csv('sample_data.csv')
print(df)

    employee_id             name   department   age    salary   join_date  \
0           101      Ayesha Khan        Sales  29.0   52000.0  2019-03-15
1           102      Bilal Ahmed  Engineering  34.0   78000.0  2017-06-01
2           103       Sana Malik    Marketing  26.0   45000.0  2021-01-10
3           104      Omar Farooq  Engineering  41.0   95000.0  2013-11-23
4           105     Fatima Iqbal           HR  31.0   50000.0  2018-08-05
5           106      Hassan Raza        Sales  25.0   41000.0  2022-04-18
6           107    Zainab Sheikh      Finance  38.0   88000.0  2015-02-27
7           108      Usman Tariq  Engineering  28.0   67000.0  2020-09-12
8           109    Mahnoor Aslam    Marketing  33.0   54000.0  2016-07-30
9           110        Ali Hyder      Finance  45.0  102000.0  2011-05-19
10          111      Hina Yousuf           HR  27.0       NaN  2021-12-01
11          112    Tariq Mehmood        Sales  36.0   60000.0  2014-10-08
12          113       Nadia Aziz  Engineering  30.0   72000.0  2019-06-22
13          114  Faisal Siddiqui    Marketing   NaN   48000.0  2020-03-14
14          115   Rabia Chaudhry      Finance  39.0   91000.0  2012-01-29

         city  performance_score  is_manager
0     Karachi                4.2       False
1      Lahore                4.7        True
2   Islamabad                3.8       False
3     Karachi                4.9        True
4      Lahore                4.0       False
5     Karachi                3.5       False
6   Islamabad                4.4        True
7      Lahore                4.1       False
8     Karachi                3.9       False
9   Islamabad                4.8        True
10     Lahore                3.6       False
11    Karachi                4.3       False
12  Islamabad                4.5       False
13     Lahore                3.7       False
14    Karachi                4.6        True

In [43]:
#Selected columns
df[['name','department','age']]

               name   department   age
0       Ayesha Khan        Sales  29.0
1       Bilal Ahmed  Engineering  34.0
2        Sana Malik    Marketing  26.0
3       Omar Farooq  Engineering  41.0
4      Fatima Iqbal           HR  31.0
5       Hassan Raza        Sales  25.0
6     Zainab Sheikh      Finance  38.0
7       Usman Tariq  Engineering  28.0
8     Mahnoor Aslam    Marketing  33.0
9         Ali Hyder      Finance  45.0
10      Hina Yousuf           HR  27.0
11    Tariq Mehmood        Sales  36.0
12       Nadia Aziz  Engineering  30.0
13  Faisal Siddiqui    Marketing   NaN
14   Rabia Chaudhry      Finance  39.0

In [50]:
#sepcific column and rows
df.iloc[10:15,0:5]

    employee_id             name   department   age   salary
10          111      Hina Yousuf           HR  27.0      NaN
11          112    Tariq Mehmood        Sales  36.0  60000.0
12          113       Nadia Aziz  Engineering  30.0  72000.0
13          114  Faisal Siddiqui    Marketing   NaN  48000.0
14          115   Rabia Chaudhry      Finance  39.0  91000.0

In [71]:
df.set_index('name')

,employee_id,department,age,salary,join_date,city,performance_score,is_manager
name,,,,,,,,
Ayesha Khan,101,Sales,29.0,52000.0,2019-03-15,Karachi,4.2,False
Bilal Ahmed,102,Engineering,34.0,78000.0,2017-06-01,Lahore,4.7,True
Sana Malik,103,Marketing,26.0,45000.0,2021-01-10,Islamabad,3.8,False
Omar Farooq,104,Engineering,41.0,95000.0,2013-11-23,Karachi,4.9,True
Fatima Iqbal,105,HR,31.0,50000.0,2018-08-05,Lahore,4.0,False
Hassan Raza,106,Sales,25.0,41000.0,2022-04-18,Karachi,3.5,False
Zainab Sheikh,107,Finance,38.0,88000.0,2015-02-27,Islamabad,4.4,True
Usman Tariq,108,Engineering,28.0,67000.0,2020-09-12,Lahore,4.1,False
Mahnoor Aslam,109,Marketing,33.0,54000.0,2016-07-30,Karachi,3.9,False
Ali Hyder,110,Finance,45.0,102000.0,2011-05-19,Islamabad,4.8,True
Hina Yousuf,111,HR,27.0,NaN,2021-12-01,Lahore,3.6,False
Tariq Mehmood,112,Sales,36.0,60000.0,2014-10-08,Karachi,4.3,False
Nadia Aziz,113,Engineering,30.0,72000.0,2019-06-22,Islamabad,4.5,False
Faisal Siddiqui,114,Marketing,NaN,48000.0,2020-03-14,Lahore,3.7,False
Rabia Chaudhry,115,Finance,39.0,91000.0,2012-01-29,Karachi,4.6,True

In [89]:
high = df[df['age'] >= 35]
high.iloc[:,0:5]

    employee_id            name   department   age    salary
3           104     Omar Farooq  Engineering  41.0   95000.0
6           107   Zainab Sheikh      Finance  38.0   88000.0
9           110       Ali Hyder      Finance  45.0  102000.0
11          112   Tariq Mehmood        Sales  36.0   60000.0
14          115  Rabia Chaudhry      Finance  39.0   91000.0

In [91]:
lahore_high = df[(df['city'] == 'Lahore') & (df['age'] >= 25)]
lahore_high.iloc[:,0:5]

    employee_id          name   department   age   salary
1           102   Bilal Ahmed  Engineering  34.0  78000.0
4           105  Fatima Iqbal           HR  31.0  50000.0
7           108   Usman Tariq  Engineering  28.0  67000.0
10          111   Hina Yousuf           HR  27.0      NaN

In [118]:
df['performance'] = df['performance_score']
df['percentage'] = df['performance_score'] / 5 *100
df['City_key'] = df['city'].map({'Lahore':1, 'Karachi':2 , 'Islamabad':3})
df.iloc[:,4:]

,salary,join_date,city,performance_score,is_manager,Code,performance,percentage,City_key
0,52000.0,2019-03-15,Karachi,4.2,False,False,4.2,84.0,2
1,78000.0,2017-06-01,Lahore,4.7,True,True,4.7,94.0,1
2,45000.0,2021-01-10,Islamabad,3.8,False,False,3.8,76.0,3
3,95000.0,2013-11-23,Karachi,4.9,True,False,4.9,98.0,2
4,50000.0,2018-08-05,Lahore,4.0,False,True,4.0,80.0,1
5,41000.0,2022-04-18,Karachi,3.5,False,False,3.5,70.0,2
6,88000.0,2015-02-27,Islamabad,4.4,True,False,4.4,88.0,3
7,67000.0,2020-09-12,Lahore,4.1,False,True,4.1,82.0,1
8,54000.0,2016-07-30,Karachi,3.9,False,False,3.9,78.0,2
9,102000.0,2011-05-19,Islamabad,4.8,True,False,4.8,96.0,3
10,NaN,2021-12-01,Lahore,3.6,False,True,3.6,72.0,1
11,60000.0,2014-10-08,Karachi,4.3,False,False,4.3,86.0,2
12,72000.0,2019-06-22,Islamabad,4.5,False,False,4.5,90.0,3
13,48000.0,2020-03-14,Lahore,3.7,False,True,3.7,74.0,1
14,91000.0,2012-01-29,Karachi,4.6,True,False,4.6,92.0,2

In [126]:
df.sort_values(['name'],ascending=[True])

,employee_id,name,department,age,salary,join_date,city,performance_score,is_manager,Code,performance,percentage,City_key
9,110,Ali Hyder,Finance,45.0,102000.0,2011-05-19,Islamabad,4.8,True,False,4.8,96.0,3
0,101,Ayesha Khan,Sales,29.0,52000.0,2019-03-15,Karachi,4.2,False,False,4.2,84.0,2
1,102,Bilal Ahmed,Engineering,34.0,78000.0,2017-06-01,Lahore,4.7,True,True,4.7,94.0,1
13,114,Faisal Siddiqui,Marketing,NaN,48000.0,2020-03-14,Lahore,3.7,False,True,3.7,74.0,1
4,105,Fatima Iqbal,HR,31.0,50000.0,2018-08-05,Lahore,4.0,False,True,4.0,80.0,1
5,106,Hassan Raza,Sales,25.0,41000.0,2022-04-18,Karachi,3.5,False,False,3.5,70.0,2
10,111,Hina Yousuf,HR,27.0,NaN,2021-12-01,Lahore,3.6,False,True,3.6,72.0,1
8,109,Mahnoor Aslam,Marketing,33.0,54000.0,2016-07-30,Karachi,3.9,False,False,3.9,78.0,2
12,113,Nadia Aziz,Engineering,30.0,72000.0,2019-06-22,Islamabad,4.5,False,False,4.5,90.0,3
3,104,Omar Farooq,Engineering,41.0,95000.0,2013-11-23,Karachi,4.9,True,False,4.9,98.0,2
14,115,Rabia Chaudhry,Finance,39.0,91000.0,2012-01-29,Karachi,4.6,True,False,4.6,92.0,2
2,103,Sana Malik,Marketing,26.0,45000.0,2021-01-10,Islamabad,3.8,False,False,3.8,76.0,3
11,112,Tariq Mehmood,Sales,36.0,60000.0,2014-10-08,Karachi,4.3,False,False,4.3,86.0,2
7,108,Usman Tariq,Engineering,28.0,67000.0,2020-09-12,Lahore,4.1,False,True,4.1,82.0,1
6,107,Zainab Sheikh,Finance,38.0,88000.0,2015-02-27,Islamabad,4.4,True,False,4.4,88.0,3

In [129]:
df.sort_values(['age'])

,employee_id,name,department,age,salary,join_date,city,performance_score,is_manager,Code,performance,percentage,City_key
5,106,Hassan Raza,Sales,25.0,41000.0,2022-04-18,Karachi,3.5,False,False,3.5,70.0,2
2,103,Sana Malik,Marketing,26.0,45000.0,2021-01-10,Islamabad,3.8,False,False,3.8,76.0,3
10,111,Hina Yousuf,HR,27.0,NaN,2021-12-01,Lahore,3.6,False,True,3.6,72.0,1
7,108,Usman Tariq,Engineering,28.0,67000.0,2020-09-12,Lahore,4.1,False,True,4.1,82.0,1
0,101,Ayesha Khan,Sales,29.0,52000.0,2019-03-15,Karachi,4.2,False,False,4.2,84.0,2
12,113,Nadia Aziz,Engineering,30.0,72000.0,2019-06-22,Islamabad,4.5,False,False,4.5,90.0,3
4,105,Fatima Iqbal,HR,31.0,50000.0,2018-08-05,Lahore,4.0,False,True,4.0,80.0,1
8,109,Mahnoor Aslam,Marketing,33.0,54000.0,2016-07-30,Karachi,3.9,False,False,3.9,78.0,2
1,102,Bilal Ahmed,Engineering,34.0,78000.0,2017-06-01,Lahore,4.7,True,True,4.7,94.0,1
11,112,Tariq Mehmood,Sales,36.0,60000.0,2014-10-08,Karachi,4.3,False,False,4.3,86.0,2
6,107,Zainab Sheikh,Finance,38.0,88000.0,2015-02-27,Islamabad,4.4,True,False,4.4,88.0,3
14,115,Rabia Chaudhry,Finance,39.0,91000.0,2012-01-29,Karachi,4.6,True,False,4.6,92.0,2
3,104,Omar Farooq,Engineering,41.0,95000.0,2013-11-23,Karachi,4.9,True,False,4.9,98.0,2
9,110,Ali Hyder,Finance,45.0,102000.0,2011-05-19,Islamabad,4.8,True,False,4.8,96.0,3
13,114,Faisal Siddiqui,Marketing,NaN,48000.0,2020-03-14,Lahore,3.7,False,True,3.7,74.0,1

In [132]:
df.rename(columns={'performance': 'stand'}, inplace=True)
def salary_check(salary):
    if salary >= 80000:
        return 'Excellent'
    elif salary >= 50000:
        return 'Good'
    else:
        return 'Fine'

df['salary_grade'] = df['salary'].apply(salary_check)

df

,employee_id,name,department,age,salary,join_date,city,performance_score,is_manager,Code,stand,percentage,City_key,salary_grade
0,101,Ayesha Khan,Sales,29.0,52000.0,2019-03-15,Karachi,4.2,False,False,4.2,84.0,2,Good
1,102,Bilal Ahmed,Engineering,34.0,78000.0,2017-06-01,Lahore,4.7,True,True,4.7,94.0,1,Good
2,103,Sana Malik,Marketing,26.0,45000.0,2021-01-10,Islamabad,3.8,False,False,3.8,76.0,3,Fine
3,104,Omar Farooq,Engineering,41.0,95000.0,2013-11-23,Karachi,4.9,True,False,4.9,98.0,2,Excellent
4,105,Fatima Iqbal,HR,31.0,50000.0,2018-08-05,Lahore,4.0,False,True,4.0,80.0,1,Good
5,106,Hassan Raza,Sales,25.0,41000.0,2022-04-18,Karachi,3.5,False,False,3.5,70.0,2,Fine
6,107,Zainab Sheikh,Finance,38.0,88000.0,2015-02-27,Islamabad,4.4,True,False,4.4,88.0,3,Excellent
7,108,Usman Tariq,Engineering,28.0,67000.0,2020-09-12,Lahore,4.1,False,True,4.1,82.0,1,Good
8,109,Mahnoor Aslam,Marketing,33.0,54000.0,2016-07-30,Karachi,3.9,False,False,3.9,78.0,2,Good
9,110,Ali Hyder,Finance,45.0,102000.0,2011-05-19,Islamabad,4.8,True,False,4.8,96.0,3,Excellent
10,111,Hina Yousuf,HR,27.0,NaN,2021-12-01,Lahore,3.6,False,True,3.6,72.0,1,Fine
11,112,Tariq Mehmood,Sales,36.0,60000.0,2014-10-08,Karachi,4.3,False,False,4.3,86.0,2,Good
12,113,Nadia Aziz,Engineering,30.0,72000.0,2019-06-22,Islamabad,4.5,False,False,4.5,90.0,3,Good
13,114,Faisal Siddiqui,Marketing,NaN,48000.0,2020-03-14,Lahore,3.7,False,True,3.7,74.0,1,Fine
14,115,Rabia Chaudhry,Finance,39.0,91000.0,2012-01-29,Karachi,4.6,True,False,4.6,92.0,2,Excellent