# Data Science Practice Notebook
### Lecture 1: NumPy  •  Lecture 2: Pandas I

**Level:** Beginner → Intermediate

**How to use this notebook**
- Read the short concept notes, then **run** each worked example and study the output.
- The **Tasks** sections have empty cells for you to write your own code.
- A separate *Solutions* notebook contains full answers — try the tasks yourself first!

**Before Lecture 2:** download the **Titanic** dataset from Kaggle
(https://www.kaggle.com/c/titanic/data), rename the training file to `titanic.csv`,
and place it in the **same folder** as this notebook.

---
# Lecture 1 — NumPy

NumPy is the core library for numerical computing in Python. It gives us the fast, memory-efficient **ndarray** and a huge set of vectorized operations.

In [14]:
import numpy as np
print(np.__version__)

2.5.2

## 1.1 Creating Arrays

Arrays can be built from Python lists or generated with helper functions.

In [15]:
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)

# 2D array (matrix) from nested lists
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("2D array:\n", m)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]

In [16]:
# Generator functions
print("zeros:\n", np.zeros((2, 3)))
print("ones:\n", np.ones((2, 2)))
print("full:\n", np.full((2, 2), 7))
print("arange:", np.arange(0, 10, 2))        # start, stop, step
print("linspace:", np.linspace(0, 1, 5))     # 5 evenly spaced points 0..1
print("identity:\n", np.eye(3))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]]
full:
 [[7 7]
 [7 7]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### Array attributes
Every array knows its shape, dimensions, size, and data type.

In [17]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("shape :", m.shape)   # (rows, cols)
print("ndim  :", m.ndim)    # number of dimensions
print("size  :", m.size)    # total elements
print("dtype :", m.dtype)   # data type

shape : (2, 3)
ndim  : 2
size  : 6
dtype : int64

### Reshaping
Change the layout of the data without changing the values.

In [18]:
a = np.arange(12)
print("original:", a)
print("reshaped 3x4:\n", a.reshape(3, 4))
print("transpose:\n", a.reshape(3, 4).T)
print("flatten:", a.reshape(3, 4).flatten())

original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]

## 1.2 Indexing & Slicing

Select single elements, ranges, or elements matching a condition.

In [19]:
a = np.array([10, 20, 30, 40, 50])
print("first     :", a[0])
print("last      :", a[-1])
print("slice 1:4 :", a[1:4])
print("every 2nd :", a[::2])

first     : 10
last      : 50
slice 1:4 : [20 30 40]
every 2nd : [10 30 50]

In [20]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("element (row1,col2):", m[2, 2])
print("whole row 0        :", m[0])
print("whole col 1        :", m[:, 1])
print("sub-matrix top-left 2x2:\n", m[:2, :2])

element (row1,col2): 9
whole row 0        : [1 2 3]
whole col 1        : [2 5 8]
sub-matrix top-left 2x2:
 [[1 2]
 [4 5]]

### Boolean (mask) indexing
Use a condition to pull out matching elements.

In [21]:
a = np.array([5, 12, 7, 20, 3, 18])
mask = a > 10
print("mask       :", mask)
print("values >10 :", a[mask])
print("shortcut   :", a[a > 10])

# np.where: choose values based on a condition
print("clip:", np.where(a > 10, a, 0))   # keep if >10 else 0

mask       : [False  True False  True False  True]
values >10 : [12 20 18]
shortcut   : [12 20 18]
clip: [ 0 12  0 20  0 18]

### Fancy indexing
Index with an array of positions.

In [22]:
a = np.array([100, 200, 300, 400, 500])
idx = [0, 2, 4]
print(a[idx])

[100 300 500]

## 1.3 Broadcasting

Broadcasting lets NumPy apply operations between arrays of **different shapes** by
automatically stretching the smaller one. Rule of thumb: dimensions are compatible when they are
**equal** or one of them is **1**.

In [23]:
a = np.array([1, 2, 3, 4])
print("array + scalar:", a + 10)     # scalar stretched to every element
print("array * 2     :", a * 2)

array + scalar: [11 12 13 14]
array * 2     : [2 4 6 8]

In [24]:
# Row + column broadcasting -> 3x3 grid
col = np.array([[0], [10], [20]])    # shape (3,1)
row = np.array([1, 2, 3])            # shape (3,)
print("col shape:", col.shape, "row shape:", row.shape)
print("broadcast sum:\n", col + row)

col shape: (3, 1) row shape: (3,)
broadcast sum:
 [[ 1  2  3]
 [11 12 13]
 [21 22 23]]

In [25]:
# Practical example: subtract the mean of each column
data = np.array([[10, 20, 30],
                 [40, 50, 60]])
col_means = data.mean(axis=0)
print("column means:", col_means)
print("centered:\n", data - col_means)

column means: [25. 35. 45.]
centered:
 [[-15. -15. -15.]
 [ 15.  15.  15.]]

## 1.4 Operations & Aggregations

Arithmetic is element-wise; aggregations can run over the whole array or along an axis.

In [26]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("add:", a + b)
print("mul:", a * b)
print("sqrt:", np.sqrt(b))
print("exp :", np.round(np.exp(a), 2))

add: [11 22 33]
mul: [10 40 90]
sqrt: [3.16227766 4.47213595 5.47722558]
exp : [ 2.72  7.39 20.09]

In [27]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("total sum :", m.sum())
print("mean      :", m.mean())
print("std        :", round(m.std(), 3))
print("sum axis=0 (down columns):", m.sum(axis=0))
print("sum axis=1 (across rows) :", m.sum(axis=1))
print("max:", m.max(), " argmax(flat index):", m.argmax())

total sum : 21
mean      : 3.5
std        : 1.708
sum axis=0 (down columns): [5 7 9]
sum axis=1 (across rows) : [ 6 15]
max: 6  argmax(flat index): 5

---
## 🧪 Lecture 1 Tasks — NumPy

Write your code in the empty cells. Try everything yourself before checking the Solutions notebook.

**Quick drills:** Tasks 1–3   •   **Challenges:** Tasks 4–5

**Task 1 (drill).** Create a 1D array of the even numbers from 2 to 20 (inclusive). Print the array, its shape, and its dtype.

In [28]:
import numpy as np

arr = np.arange(2, 21, 2)

print(arr)
print(arr.shape)
print(arr.dtype)

[ 2  4  6  8 10 12 14 16 18 20]
(10,)
int64

**Task 2 (drill).** Create a 3×3 matrix containing the numbers 1 through 9. Then extract (a) the middle row, (b) the last column, and (c) the top-left 2×2 block.

In [29]:
import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)

print("Matrix:")
print(matrix)

middle_row = matrix[1, :]
print("Middle row:")
print(middle_row)

last_column = matrix[:, 2]
print("Last column:")
print(last_column)

top_left = matrix[:2, :2]
print("Top-left 2×2 block:")
print(top_left)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Middle row:
[4 5 6]
Last column:
[3 6 9]
Top-left 2×2 block:
[[1 2]
 [4 5]]

**Task 3 (drill).** Given `scores = np.array([45, 88, 72, 60, 95, 33, 78])`, use boolean indexing to print only the passing scores (>= 50) and count how many passed.

In [30]:
import numpy as np

scores = np.array([45, 88, 72, 60, 95, 33, 78])

passing_scores = scores[scores >= 50]

print("Passing scores:", passing_scores)

print("Number of students passed:", len(passing_scores))

Passing scores: [88 72 60 95 78]
Number of students passed: 5

**Task 4 (challenge).** You are given a 4×3 array of raw measurements below. Using **broadcasting**, normalise each **column** so it has mean 0 and standard deviation 1 (i.e. subtract the column mean and divide by the column std). Verify by printing the new column means (≈0) and stds (≈1).

```python
data = np.array([[12, 200, 5],
                 [15, 240, 7],
                 [11, 210, 6],
                 [18, 260, 9]], dtype=float)
```

In [31]:
import numpy as np

data = np.array([[12, 200, 5],
                 [15, 240, 7],
                 [11, 210, 6],
                 [18, 260, 9]], dtype=float)

column_means = data.mean(axis=0)

column_stds = data.std(axis=0)

normalised = (data - column_means) / column_stds

print("Normalised data:")
print(normalised)

print("New colum means:")
print(normalised.mean(axis=0))

print("New column stds:")
print(normalised.std(axis=0))

Normalised data:
[[-0.73029674 -1.15311332 -1.18321596]
 [ 0.36514837  0.52414242  0.16903085]
 [-1.09544512 -0.73379939 -0.50709255]
 [ 1.46059349  1.36277029  1.52127766]]
New colum means:
[0. 0. 0.]
New column stds:
[1. 1. 1.]

**Task 5 (challenge).** Simulate rolling two dice 1000 times.
1. Use `np.random.seed(42)` for reproducibility.
2. Create two arrays of 1000 random integers in the range 1–6.
3. Compute the sum of each pair.
4. Report: the mean total, and the fraction of rolls where the total was exactly 7.

In [32]:
import numpy as np

np.random.seed(42)

die1 = np.random.randint(1, 7, size=1000)
die2 = np.random.randint(1, 7, size=1000)

totals = die1 + die2

mean_total = totals.mean()

fraction_seven = np.mean(totals == 7)

print("Mean total:", mean_total)
print("Fraction of rolls with total 7:", fraction_seven)

Mean total: 6.957
Fraction of rolls with total 7: 0.174

---
# Lecture 2 — Pandas I

Pandas builds on NumPy to give us labelled, table-like data structures: the 1D **Series** and the 2D **DataFrame**. This is the workhorse for data cleaning and analysis.

In [33]:
import pandas as pd
import numpy as np
print(pd.__version__)

3.0.5

## 2.1 Series & DataFrame

A **Series** is a labelled 1D column. A **DataFrame** is a collection of Series sharing an index.

In [34]:
# Series from a list (default integer index)
s = pd.Series([10, 20, 30, 40])
print(s)

# Series with a custom index
s2 = pd.Series([85, 90, 78], index=["Ali", "Sara", "Zed"])
print("\nSara's score:", s2["Sara"])

0    10
1    20
2    30
3    40
dtype: int64

Sara's score: 90

In [35]:
# DataFrame from a dict of columns
df = pd.DataFrame({
    "name":  ["Ali", "Sara", "Zed", "Mina"],
    "age":   [23, 35, 29, 41],
    "city":  ["Lahore", "Karachi", "Lahore", "Quetta"],
    "score": [85, 90, 78, 88],
})
df

   name  age     city  score
0   Ali   23   Lahore     85
1  Sara   35  Karachi     90
2   Zed   29   Lahore     78
3  Mina   41   Quetta     88

### Inspecting a DataFrame

In [36]:
print("shape:", df.shape)
print("columns:", list(df.columns))
print("dtypes:\n", df.dtypes)
df.head(2)

shape: (4, 4)
columns: ['name', 'age', 'city', 'score']
dtypes:
 name       str
age      int64
city       str
score    int64
dtype: object

   name  age     city  score
0   Ali   23   Lahore     85
1  Sara   35  Karachi     90

In [37]:
df.describe()   # summary stats for numeric columns

             age      score
count   4.000000   4.000000
mean   32.000000  85.250000
std     7.745967   5.251984
min    23.000000  78.000000
25%    27.500000  83.250000
50%    32.000000  86.500000
75%    36.500000  88.500000
max    41.000000  90.000000

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
 3   score   4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

## 2.2 Selection

Select columns by name, and rows/cells with `.loc` (labels) or `.iloc` (positions).

In [39]:
# Column selection
print(df["name"])            # single column -> Series
df[["name", "score"]]        # multiple columns -> DataFrame

0     Ali
1    Sara
2     Zed
3    Mina
Name: name, dtype: str

   name  score
0   Ali     85
1  Sara     90
2   Zed     78
3  Mina     88

In [40]:
# .loc  -> label based  |  .iloc -> position based
print("loc row 0:\n", df.loc[0])
print("\niloc row 0:\n", df.iloc[0])
print("\nloc rows 0-2, name+score:\n", df.loc[0:2, ["name", "score"]])

loc row 0:
 name        Ali
age          23
city     Lahore
score        85
Name: 0, dtype: object

iloc row 0:
 name        Ali
age          23
city     Lahore
score        85
Name: 0, dtype: object

loc rows 0-2, name+score:
    name  score
0   Ali     85
1  Sara     90
2   Zed     78

### Boolean filtering
Select rows that match a condition.

In [41]:
print(df[df["age"] > 30])
print("\nLahore residents scoring > 80:")
df[(df["city"] == "Lahore") & (df["score"] > 80)]

   name  age     city  score
1  Sara   35  Karachi     90
3  Mina   41   Quetta     88

Lahore residents scoring > 80:

  name  age    city  score
0  Ali   23  Lahore     85

### Setting / resetting the index

In [42]:
df_idx = df.set_index("name")
print(df_idx.loc["Sara"])
df_idx.reset_index().head()

age           35
city     Karachi
score         90
Name: Sara, dtype: object

   name  age     city  score
0   Ali   23   Lahore     85
1  Sara   35  Karachi     90
2   Zed   29   Lahore     78
3  Mina   41   Quetta     88

## 2.3 Cleaning

Real data is messy. Common fixes: rename columns, fix types, drop duplicates, tidy strings, apply functions.

In [43]:
messy = pd.DataFrame({
    "Full Name": [" ali ", "SARA", "Zed", "Zed"],
    "Age":       ["23", "35", "29", "29"],
    "City":      ["lahore", "karachi", "lahore", "lahore"],
})
messy

  Full Name Age     City
0      ali   23   lahore
1      SARA  35  karachi
2       Zed  29   lahore
3       Zed  29   lahore

In [44]:
# Rename columns to clean, lowercase names
messy = messy.rename(columns={"Full Name": "name", "Age": "age", "City": "city"})

# Fix a data type: age is stored as text -> convert to int
messy["age"] = messy["age"].astype(int)

# Tidy strings: strip spaces + title-case names, title-case cities
messy["name"] = messy["name"].str.strip().str.title()
messy["city"] = messy["city"].str.title()

# Remove duplicate rows
messy = messy.drop_duplicates()
messy

   name  age     city
0   Ali   23   Lahore
1  Sara   35  Karachi
2   Zed   29   Lahore

### Apply / map — transform values with a function

In [45]:
df["score_grade"] = df["score"].apply(lambda x: "A" if x >= 85 else "B")
df

   name  age     city  score score_grade
0   Ali   23   Lahore     85           A
1  Sara   35  Karachi     90           A
2   Zed   29   Lahore     78           B
3  Mina   41   Quetta     88           A

## 2.4 Missing Data

`NaN` marks missing values. Detect them, drop them, or fill them.

In [46]:
nd = pd.DataFrame({
    "name":  ["Ali", "Sara", "Zed", "Mina"],
    "age":   [23, np.nan, 29, np.nan],
    "score": [85, 90, np.nan, 88],
})
nd

   name   age  score
0   Ali  23.0   85.0
1  Sara   NaN   90.0
2   Zed  29.0    NaN
3  Mina   NaN   88.0

In [47]:
# Detect missing values
print(nd.isnull())
print("\nmissing per column:\n", nd.isnull().sum())

    name    age  score
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

missing per column:
 name     0
age      2
score    1
dtype: int64

In [48]:
# Drop rows containing any NaN
print("dropna (rows):\n", nd.dropna())

# Fill missing 'age' with the column mean; fill 'score' with 0
filled = nd.copy()
filled["age"] = filled["age"].fillna(filled["age"].mean())
filled["score"] = filled["score"].fillna(0)
filled

dropna (rows):
   name   age  score
0  Ali  23.0   85.0

   name   age  score
0   Ali  23.0   85.0
1  Sara  26.0   90.0
2   Zed  29.0    0.0
3  Mina  26.0   88.0

---
## 🧪 Lecture 2 Tasks — Pandas I (Titanic dataset)

Download the Titanic training data from Kaggle
(https://www.kaggle.com/c/titanic/data), save it as **`titanic.csv`** next to this
notebook, then run the loader cell below.

**Quick drills:** Tasks 1–3   •   **Challenges:** Tasks 4–5

In [49]:
import pandas as pd
import numpy as np

# Load the dataset (make sure titanic.csv is in the same folder)
titanic = pd.read_csv("titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Task 1 (drill).** Display the shape of the dataset, the list of column names, and the data type of each column.

In [50]:
import pandas as pd

df = pd.read_csv("titanic.csv")

print("Dataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Dataset shape:
(891, 12)

Column names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Data types:
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

**Task 2 (drill).** Select and display only the `Name`, `Sex`, `Age`, and `Survived` columns for the first 10 passengers.

In [51]:
df[["Name", "Sex", "Age", "Survived"]].head(10)

                                                Name     Sex   Age  Survived
0                            Braund, Mr. Owen Harris    male  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                             Heikkinen, Miss. Laina  female  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                           Allen, Mr. William Henry    male  35.0         0
5                                   Moran, Mr. James    male   NaN         0
6                            McCarthy, Mr. Timothy J    male  54.0         0
7                     Palsson, Master. Gosta Leonard    male   2.0         0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0         1
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0         1

**Task 3 (drill).** How many missing values are in each column? Which column has the most missing values?

In [52]:
missing = df.isnull().sum()
print("Missing values per column:")
print(missing)

print("\nColumn with most missing values:", missing.idxmax())

Missing values per column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Column with most missing values: Cabin

**Task 4 (challenge).** Clean the dataset:
1. Fill missing `Age` values with the **median** age.
2. Fill missing `Embarked` values with the **mode** (most common port).
3. Drop the `Cabin` column (too many missing values).
4. Confirm there are no missing values left in `Age` and `Embarked`.

In [53]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df = df.drop(columns=["Cabin"])

print("Missing values left:")
print(df[["Age", "Embarked"]].isnull().sum())

Missing values left:
Age         0
Embarked    0
dtype: int64

**Task 5 (challenge).** Using boolean filtering and selection, answer:
1. What fraction of all passengers survived?
2. Compare survival rate for females vs males.
3. Among passengers **under 18**, what was the survival rate?
*(Hint: `Survived` is 1/0, so its mean is the survival rate.)*

In [54]:
overall_rate = df["Survived"].mean()
print("Overall survival rate:", overall_rate)

female_rate = df[df["Sex"] == "female"]["Survived"].mean()
male_rate = df[df["Sex"] == "male"]["Survived"].mean()
print("\nFemale survival rate:", female_rate)
print("Male survival rate:", male_rate)

under_18_rate = df[df["Age"] < 18]["Survived"].mean()
print("\nUnder-18 survival rate:", under_18_rate)

Overall survival rate: 0.3838383838383838

Female survival rate: 0.7420382165605095
Male survival rate: 0.18890814558058924

Under-18 survival rate: 0.5398230088495575